branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode8
cache:
  - cocoapods
install: bundle install

jobs:
  include:
    - stage: test
      env: TEST_TYPE=iOS
      script: 
      - | 
          set -o pipefail
          xcodebuild build -workspace ParseLiveQuery.xcworkspace -sdk iphonesimulator -scheme ParseLiveQuery-iOS -configuration Debug -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: test
      env: TEST_TYPE=OSX
      script: 
      - | 
          set -o pipefail
          xcodebuild build -workspace ParseLiveQuery.xcworkspace -sdk macosx -scheme ParseLiveQuery-OSX -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: test
      env: TEST_TYPE=OSXDemoSwift
      script: 
      - | 
          set -o pipefail
          xcodebuild clean -workspace ParseLiveQuery.xcworkspace -scheme LiveQueryDemo | xcpretty -c
          xcodebuild build -workspace ParseLiveQuery.xcworkspace -scheme LiveQueryDemo -configuration Debug | xcpretty -c
    - stage: test
      env: TEST_TYPE=OSXDemoObjC
      script: 
      - | 
          set -o pipefail
          xcodebuild clean -workspace ParseLiveQuery.xcworkspace -scheme LiveQueryDemo-ObjC | xcpretty -c
          xcodebuild build -workspace ParseLiveQuery.xcworkspace -scheme LiveQueryDemo-ObjC -configuration Debug | xcpretty -c
    - stage: test
      env: TEST_TYPE=CocoaPods
      script: 
      - | 
          bundle exec pod repo update 2>&1 || exit 1
          pod lib lint ParseLiveQuery.podspec 
    - stage: test
      env: TEST_TYPE=Carthage
      script: carthage build --no-skip-current
